### ISSUE TITLE
Design, Metrics and configuration

### ISSUE THREAD

**Issue by riklempens** [oversight/dnsprobe#1]
## Config

* `fqdn` (Optional) (or hostname) e.g. `host.cesbit.com`
* `ptr` (Optional) e.g. `103.254.241.192.in-addr.arpa`
* `nameServers` (Optional) DNS server(s) to query (if left empty the DNS from the appliance is used)

When an IPv4 or IPv6 address is entered we only perform a PTR lookup.

Example query for all times in one shot using the name server `8.8.8.8`:

```
export fqdn=siridb.com && dig @8.8.8.8 $fqdn A $fqdn AAAA $fqdn CNAME $fqdn MX $fqdn NS $fqdn PTR $fqdn SRV $fqdn SOA $fqdn TXT $fqdn CAA $fqdn DS $fqdn DNSKEY
```

### A
_requires fqdn_

List of IPv4 addresses and TTL.

TTL | address
----|---------
176 | 142.250.65.206
176 | 142.250.65.207

### AAAA
_requires fqdn_

List of IPv6 addresses and TTL.

TTL | address
----|---------
300 | 2001:0db8:85a3:0000:0000:8a2e:0370:7334
300 | f8b0:4006:81e::200e

### CNAME
_requires fqdn_

A CNAME lookup can only return **one** canonical name.

TTL: 3600
siridb.com

### MX
_requires fqdn_

List of MX records.

TTL  | preference | address
-----|------------|-------------------------
3600 | 1          | aspmx.l.google.com
3600 | 5          | alt1.aspmx.l.google.com
3600 | 5          | alt2.aspmx.l.google.com
3600 | 10         | alt3.aspmx.l.google.com
3600 | 10         | alt4.aspmx.l.google.com

### NS
_requires fqdn_

List of name servers.

TTL   | address
------|------------------------------
21600 | ns-cloud-a1.googledomains.com
21600 | ns-cloud-a2.googledomains.com
21600 | ns-cloud-a3.googledomains.com
21600 | ns-cloud-a4.googledomains.com

### PTR
_requires ptr_

reverse DNS records

Only possible for IP addresses in the format: `8.8.8.8.in-addr.arpa.`

Example query: `dig 8.8.8.8.in-addr.arpa. PTR`, you can also use: dig -x 8.8.8.8

dig 

TTL   | address
------|------------------------
20557 | dns.google.

### SRV
_requires fqdn_

[source](https://en.wikipedia.org/wiki/SRV_record)

example query: `dig _sip._tls.o365.test-technology.nl srv`

List of SRV records

TTL | Priority | Weight | Port | Target
----|----------|--------|------|------
300 | 100      | 1      | 443  | sipdir.online.lync.com

### SOA
_requires fqdn_

Type | Domain Name | TTL  | Primary NS       | Responsible name      | Serial     | Refresh | Retry | Expire  | Miniumum
-----|-------------|------|------------------|-----------------------|------------|---------|-------|---------|----------
SOA  | cesbit.com  | 3600 | ns0.transip.net. | hostmaster.transip.nl.| 2022013100 | 86400   | 1800  | 2419200 | 300

#### Structure

[source](https://en.wikipedia.org/wiki/SOA_record)

- **NAME**
  Name of the zone
- **TYPE**
  SOA, abbreviation for start of authority
- **CLASS**
  Zone class (all but universally IN for internet)
- **TTL**
  Time-to-live
- **MNAME**
  Primary master name server for this zone.
- **RNAME**
  Email address of the administrator responsible for this zone. (As usual, the email address is encoded as a name. The part of the email address before the @ becomes the first label of the name; the domain name after the @ becomes the rest of the name. In zone-file format, dots in labels are escaped with backslashes; thus the email address john.doe@example.com would be represented in a zone file as john\.doe.example.com.)
- **SERIAL**
  Serial number for this zone. If a secondary name server slaved to this one observes an increase in this number, the slave will assume that the zone has been updated and initiate a zone transfer.
- **REFRESH**
  Number of seconds after which secondary name servers should query the master for the SOA record, to detect zone changes. Recommendation for small and stable zones:[4] 86400 seconds (24 hours).
- **RETRY**
  Number of seconds after which secondary name servers should retry to request the serial number from the master if the master does not respond. It must be less than Refresh. Recommendation for small and stable zones:[4] 7200 seconds (2 hours).
- **EXPIRE**
  Number of seconds after which secondary name servers should stop answering request for this zone if the master does not respond. This value must be bigger than the sum of Refresh and Retry. Recommendation for small and stable zones:[4] 3600000 seconds (1000 hours).
- **MINIMUM**
  Used in calculating the time to live for purposes of negative caching. Authoritative name servers take the smaller of the SOA TTL and the SOA MINIMUM to send as the SOA TTL in negative responses. Resolvers use the resulting SOA TTL to understand for how long they are allowed to cache a negative response. Recommendation for small and stable zones:[4] 172800 seconds (2 days). Originally this field had the meaning of a minimum TTL value for resource records in this zone; it was changed to its current meaning by RFC 2308.[5]

TTL
### TXT
_requires fqdn_

List of TXT records

TTL  | Record
-----|---------------------------------------------------------------------
3600 | google-site-verification=h-0WJDWxXsLa2JHnUVWclrAKdhi45UZp-x4WvW0dTCk
3600 | google-site-verification=LvYdDW4HnaK23w_u3f2s9BZp_G_Be3bTAg9Sp3Ak5Hc
3600 | v=spf1 include:_spf.google.com ~all

### CAA
_requires fqdn_

List of CAA records

TTL   | Record
------|------------------
80508 | 0 issue pki.goog

### DS
_requires fqdn_

List of DS records

TTL   | Key Tag | Algorithm | Digest Type | Digest
------|---------|-----------|-------------|------------------------------------------------------------------
21600 | 13894   | 8         | 2           | FD1466A03C0B01E65018ADF1D18F3B1D96D1010F8E24 04FC2065E489BAB47A5C

~### DNSKEY~

[source](https://docs.infoblox.com/display/NAG8/DNSKEY+Resource+Records0)
[rfc4034](https://datatracker.ietf.org/doc/html/rfc4034)

~List of DNSKEY records~

> It seems that flag could be used as name field where the value is an integer which represents either KSK or ZSK. As we do not understand what to do with this information, we do not implement the check at this moment. 

TTL | Algorithm | Protocol | Flag | Key ID | Key
----|-----------|----------|------|--------|---------------------
300 | 8         | 3        | KSK  | 13894  | AwEAAZa3hXnOjD343MMxpFxg6AlqvbwuOEUgCaX53kXG h2LOx014UTBTE2o+ZBUQ8jYxdXZjFRYXWO/9SVDX/deY NAzi3A+FXMGLG2+wJJDlO1jUz1MclBsoSaLAehkbw9RI fZjsOfh11f9ILLv08h0UxR8WXbBbhSRgpLLeBl5L21xf Gz0WuYEMoEi4EAVh2nC2hBIqRxYiAvVDlLlnq2Kzxxja mPTbAAWNzTUhSY8XMEKVA2n85vMUcEraFl6GwosCoRJt wGlxcF+lPZ0viS73vRF5kGGod4KOH0lHPc7e0mWLEVn6 DQCiZfOZnndW0amc0SYtX55zM5lfs7fjrhlp4fM=
300 | 8         | 3        | ZSK  | 42168  | AwEAAY6Q0UzJ3uLsYvjxdCR7jJzRCWXdVDaW4F+TdxiT uyNOtC3YwvmJG0dXUIlK8HrFnhbI9d8y1vGuuI/igWoe tn/kLSNz1tx9/HrezV4bVrU8VYuVuu4NaOw2QFRfjemo P8aWycd7HvdlivwGH7NHNnW644WXxO8yhcyTME3tjZ4L

## Measurement

We should also measure the time it took for the query

**Comment by riklempens** [comment]
PTR lookup IPv6 example:
```
dig 5.0.0.2.0.0.0.0.0.0.0.0.0.0.0.0.6.1.8.0.9.0.0.4.0.b.8.f.7.0.6.2.ip6.arpa. ptr +short 
ord38s09-in-x05.1e100.net.
```

**Comment by riklempens** [comment]
We should avoid using DNS caching.

**Comment by joente** [comment]
The `measuredTime` should be added to each check as type `stat` with item name `timing` and metric name `measuredTime`.

**Comment by riklempens** [comment]
configure widgets:

- [ ] A
- [ ] AAAA
- [ ] CNAME
- [ ] MX
- [ ] NS
- [ ] PTR
- [ ] SRV
- [ ] SOA
- [ ] TXT
- [ ] DS

configure conditions:

- [ ] A
- [ ] AAAA
- [ ] CNAME
- [ ] MX
- [ ] NS
- [ ] PTR
- [ ] SRV
- [ ] SOA
- [ ] TXT
- [ ] DS

**Comment by riklempens** [comment]
Closing as we migrated and improved the DNS probe in InfraSonar.
